glob: "app/**/*.{html,text,js}{+*,}.erb"
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: false
    rubocop_config:
      inherit_from:
        - .rubocop.yml
